site_name: BU Biostatics SCC Resources

nav:
    - Home: index.md
    
    
    
    
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
        - r


markdown_extensions:
  - attr_list
  - md_in_html
